#!/bin/bash

# MySQL credentials
USER="root"
PASSWORD="K!"

# Backup directory
BACKUP_DIR="/tmp"
S3_BUCKET="s3://your-s3-bucket-name/servername"

# Get list of databases (excluding system DBs)
databases=$(mysql -u "$USER" -p"$PASSWORD" -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|mysql|sys)")

# Loop through DBs
for db in $databases; do
     echo "Backing up: $db"
     mysqldump -u "$USER" -p"$PASSWORD" "$db" | gzip > "$BACKUP_DIR/$db.sql.gz"
     aws s3 cp "$BACKUP_DIR/$db.sql.gz" "$S3_BUCKET" --storage-class STANDARD_IA
    echo "Uploaded $db.sql.gz to S3"
 done

# echo "✅ All databases backed up as .sql.gz files."
