#!/bin/bash

email="ksc2704@gmail.com , abhishek.shodhan@discus.solutions"
d1=$(date --date="-5 min" +"%H:%M:%S")
d2=$(date +"%H:%M:%S")
echo $d1
echo $d2
errors=$(cat /home/ubuntu/Servers/server9190_talent/wildfly-10.1.0.Final/standalone/log/server.log | awk -v d1="$d1" -v d2="$d2" '$0 > d1 && $0 < d2 || $0 ~ d2' | grep -a "ERROR\|FATAL\|Exception\|at.*\.java\:.*" | grep -v -e "WARN" -e "INFO")
if [ -z "$errors" ]; then
echo "No error Found."
exit;
fi
subject="JBOSS DAILY ERROR LOG FOR:TALENT QUALITY Server-9190"
sed -i '6s/quality-noreply/TALENT QUALITY Error Watch/' ~/.mutt/muttrc
echo "$errors" | mutt -s "$subject" "$email"
sed -i '6s/TALENT QUALITY Error Watch/quality-noreply/' ~/.mutt/muttrc
